### ISSUE TITLE
Support for proxy?

### ISSUE THREAD

**Issue by ruffp** [sulaweyo/http_download#2]
I cannot make it work because I need to set up proxy settings in my local network.

Is there any Proxy support in this module?
If the module support Proxy setting I suggest to add an example.

It is very interesting as it does not need anything else than ruby and no external software.

**Comment by sulaweyo** [comment]
I did not have the need for it so far but if i read the doc correctly this should be very easy to do:
http://ruby-doc.org/stdlib-2.3.0/libdoc/net/http/rdoc/Net/HTTP.html and it is in for old ruby versions (like ubuntu 12.04) as well http://ruby-doc.org/stdlib-1.8.7/libdoc/net/http/rdoc/Net/HTTP.html

So basically it really just has to be added. I'll happily merge a pull request or i'll have a look myself when i find the time.

**Comment by ruffp** [comment]
Thanks for your answer... Unfortunately I am not very experienced with ruby but I'll try using your links and a fork of your project. If I succeed to make it work, I will make a PR.

**Comment by sulaweyo** [comment]
No need to spend a lot of time ... i'll see if i get to it that weekend ;)

**Comment by sulaweyo** [comment]
Uploaded new release 0.1.7 to forge
