### ISSUE TITLE
when error happens puppet finishes with success status

### ISSUE THREAD

**Issue by standagh** [sulaweyo/http_download#4]
Even though I use invalid hostname in url download 3times tries to download file from URL and 3 times fails. But output of puppet apply is success (return code '0' on command line) even though --detailed-exitcodes is used
https://docs.puppet.com/puppet/4.6/man/apply.html

Puppet agent version:
puppet-agent-1.5.3-1.el7.x86_64

If I looked correctly download providers method 'create' is called from:
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/property/ensure.rb:16:in `block in defaultvalues'
and return value is not checked
It seems to me there is a need to raise an exception - lines from 138:
    if !succ
      raise "HTTP download of '#{resource[:uri]}' failed!"
    end
    succ
  end

**Comment by standagh** [comment]
Actually just created pull request with proposed change

**Comment by sulaweyo** [comment]
Merged your PR #5
